{% set version = "0.23.3" %}

package:
  name: openpiv
  version: {{ version }}

source:
  fn: openpiv-{{ version }}.tar.gz
  url: https://github.com/OpenPIV/openpiv-python/archive/{{ version }}.tar.gz
  sha256: 1b205ba4d2712e1eb20359b9a5a0418c5f9f99d60369061c7304d4c24e8a1ebf

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - numpy
    - cython
    - requests

  run:
    - python
    - setuptools
    - cython
    - {{ pin_compatible('numpy') }}
    - scikit-image
    - future

test:
  imports:
    - openpiv

about:
  home: https://github.com/openpiv/openpiv-python
  license: GPL-3.0-only
  license_file: LICENSE.txt
  summary: Open Source Particle Image Velocimetry
  doc_url: http://openpiv.readthedocs.io/

extra:
  recipe-maintainers:
    - alexlib
