{% set version = "0.21.1b" %}

package:
  name: openpiv
  version: {{ version }}

source:
  fn: openpiv-{{ version }}.tar.gz
  url: https://github.com/OpenPIV/openpiv-python/archive/{{ version }}.tar.gz
  sha256: 95d22b53942e4dc0e0d69e648af170466bb9899c96a15ed531d14b9fb03f9373
  
build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - numpy
    - cython
    - requests

  run:
    - progressbar2
    - scikit-image
    - future

test:
  imports:
    - openpiv

about:
  home: https://github.com/openpiv/openpiv-python
  license: GPL 3
  license_file: LICENSE.txt
  summary: "Open Source Particle Image Velocimetry"
  doc_url: http://openpiv.readthedocs.io/

extra:
  recipe-maintainers:
    - alexlib
