travis:
  secure:
    BINSTAR_TOKEN: PuiAjutYnHrQKz1KH3rSQg8j/4EIh+rBdMn2J1fRlx1wS5MppNiVG0x4YnNDekYodE09/te46NjwGuVZUQOAwP5j7i3ZJtL+wmgiKAumXK/UfLoTEsZB8EdB6SO217MN5y065jnt3tMKbOgs51Dt7SVhRSADQbmXluXwcWAFqI8kNijGOj+yVkGOlkm8rrxhG7n1zy49oP5KBm6davUThNIJ1hVpoakPkGi6pOQBgNnVwbkms0hTDgjlgu7kSM8dAYK3NxFw0CnhXrk9rH10qE5gCiKQDZGzeWgq0F+FLobSBP9E3Azimey1xa7/6tANamQkinlyHpNDIvE8B28qwIKORBQbdxztc44OKNBs9/kgVa6UOillqoA+jXa7X9xKFnwsN8yWtUM9virjnfw2c5VKQTgm6LpS1C8O7F0f4kZIhttrzYJWTfwgRe4hzJ8asUBwKWkS0pDIWVtdbvFddbU157GPhaiiCQmPOeo2UHwMuNXzKeVg0SsC78zyouwThc2z3rKA1tH9ddtFRP9oVsrdTksc+auJSLv+o6y4kHhSNV97aNOO0eyNw3ZNFPN2YvnxSq5sQcI3Or0FAmzwvZQ0vO5J6q6VrjQeOthfhfi5I58tbtEMphIZasH7byT/xdrkAZmTEdK4gx/Nh7ibyqfloh/qd5S7wXGmgP934ZM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
